### ISSUE TITLE
configured as anon doesn't work

### ISSUE THREAD

**Issue by alekksander** [malteketelsen/KDE-DolphinServiceMenu-Imgur#1]
if i install and configure as anon i get this on upload:
https://i.imgur.com/C4DKQcn.png

imgurrc is empty

**Comment by malteketelsen** [comment]
I have no problems there.
Did you enter the 'client id'?

![imgurconfigsh-anon](https://user-images.githubusercontent.com/15174271/50378528-ae121f00-0634-11e9-8786-361d7d03bb1e.png)

**Comment by alekksander** [comment]
yes i did, but i still get no upload url as shown on first link.

**Comment by malteketelsen** [comment]
I do not understand, you say you have entered the 'client id' and the imgurrc-file is empty. If the file is empty, it was at least created. These two commands in the imgurconfig.sh should actually do everything right:
```
read -rp "client id: " client_id  # read the id
echo "$client_id" > "$CONFIG_FILE"  # write the id in the file
```
Please check the directories with:
```
ls "${HOME}/.config/imgurrc"
ls "$(kf5-config --path services | cut -d':' -f1)ServiceMenus"
ls "$(kf5-config --path icon | cut -d':' -f1)hicolor/scalable/apps"
```

**Comment by malteketelsen** [comment]
You can manually copy your 'client id' into the imgurrc, so this is the only line, then you should be able to make anonymous uploads.

**Comment by alekksander** [comment]
![image](https://user-images.githubusercontent.com/3148302/50384199-d5fb9400-06c1-11e9-87b2-c24b4bd90167.png)
still that is what i get with only user id in imgurrc

**Comment by malteketelsen** [comment]
Please execute this command in the KDE-DolphinServiceMenu-Imgur folder:
`./dsm-imgur <path to a picture>`

**Comment by alekksander** [comment]
![image](https://user-images.githubusercontent.com/3148302/50384974-4a880000-06cd-11e9-85fa-43fafda446f5.png)

**Comment by malteketelsen** [comment]
You are missing the tool 'jq', in the README.md all dependencies are listed. For e.g. Ubuntu / Debian: `apt-get install jq`

**Comment by alekksander** [comment]
that was it. Thank You for Your time.
